groups:
- name: prometheus_node_exporter_rules
  rules:
  - expr: count without (cpu) (count without (mode) (node_cpu_seconds_total{job="node-exporter"}))
    record: instance:node_num_cpu:sum
  - expr: 1 - avg without (cpu, mode) (rate(node_cpu_seconds_total{job="node-exporter", mode="idle"}[1m]))
    record: instance:node_cpu_utilisation:rate1m
  - expr: (node_load1{job="node-exporter"} / instance:node_num_cpu:sum{job="node-exporter"})
    record: instance:node_load1_per_cpu:ratio
  - expr: 1 - (node_memory_MemAvailable_bytes{job="node-exporter"} / node_memory_MemTotal_bytes{job="node-exporter"})
    record: instance:node_memory_utilisation:ratio
  - expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes * 100)
    record: instance:node_memory_utilisation:percentage
  - expr: rate(node_vmstat_pgmajfault{job="node-exporter"}[1m])
    record: instance:node_vmstat_pgmajfault:rate1m
  - expr: rate(node_disk_io_time_seconds_total{job="node-exporter", device!=""}[1m])
    record: instance_device:node_disk_io_time_seconds:rate1m
  - expr: rate(node_disk_io_time_weighted_seconds_total{job="node-exporter", device!=""}[1m])
    record: instance_device:node_disk_io_time_weighted_seconds:rate1m
  - expr: sum without (device) (rate(node_network_receive_bytes_total{job="node-exporter", device!="lo"}[1m]))
    record: instance:node_network_receive_bytes_excluding_lo:rate1m
  - expr: sum without (device) (rate(node_network_transmit_bytes_total{job="node-exporter", device!="lo"}[1m]))
    record: instance:node_network_transmit_bytes_excluding_lo:rate1m
  - expr: sum without (device) (rate(node_network_receive_drop_total{job="node-exporter", device!="lo"}[1m]))
    record: instance:node_network_receive_drop_excluding_lo:rate1m
  - expr: sum without (device) (rate(node_network_transmit_drop_total{job="node-exporter", device!="lo"}[1m]))
    record: instance:node_network_transmit_drop_excluding_lo:rate1m
